## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function

makeCacheMatrix <- function(x = matrix()) {
	# This function is list generator that contains 4 methods:
	# 1: Method to set which matrix we are going to calculate
	# 2: Method to get the value of the matrix
	# 3: Method to set the calculated inverse of the matrix
	# 4: Method to get the calculated inverse of the matrix
	#
	# USAGE: m_ini <- makeCacheMatrix(m1)
	# Where: 
	# m1 is the matrix tp be inverted
	# m_ini is the vector generated containing the methods to set and get the 
	# values of the matrix and its inverse 

        inverse <- NULL				# Set the value of the inverse to NULL

        set <- function(y) {

                if (!identical(x,y)){		# Set the value of the matrix. If the matrix change, the value of the inverse 
                        x <<- y			# is set to NULL. If the new matrix is EXACTLY the same as the old one, then
                        inverse <<- NULL        # there is no reason to reset the cached inverse
                }				
        }

        get <- function() x					# Returns the value of the matrix
        setsolve <- function(solve) inverse <<- solve		# Set the value of the inverse 	
        getsolve <- function() inverse          		# Returns the value of the inverse

        list(set = set, get = get,				# The list of the methods
             setsolve = setsolve,
             getsolve = getsolve)
}


## Write a short comment describing this function

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
	# Depending if the matrix has been already inverted
	# returns the cached value of its inverse or it calculates
	# and store the value.

        inverse  <- x$getsolve()		# inverse is obtained from the vector generated by makeCacheMatrix

        if(!is.null(inverse)) {			# If inverse is not NULL, returns the cached value
                message("getting cached data")
                return(inverse)
        }

        data <- x$get()				# If inverse is NULL, the value of the matrix is assigned to data
        inverse <- solve(data, ...)		# The inverse of data is calculated
        x$setsolve(inverse)			# Its value is passed to the vector in order to cache its value
        inverse					# The value of the inverse is returned without showing the caching message
}
